variables :
   php :
        memory_limit=1024M
        post_max_size=128M
        upload_max_filesize=128M
        display_errors=Activé
services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.localizeddate }
